create table public.access_requests (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  full_name text not null default '',
  requested_role text not null default 'visitante'
    check (requested_role = 'visitante'),
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (project_id, user_id)
);

create index access_requests_project_status_idx
on public.access_requests (project_id, status, created_at);

alter table public.access_requests enable row level security;

-- Solicitações só podem ser lidas ou alteradas pelo serviço administrativo.
-- O cadastro público apenas cria auth.users; o trigger abaixo registra o pedido.
revoke all on table public.access_requests from public, anon, authenticated;
revoke all on sequence public.access_requests_id_seq from public, anon, authenticated;

create policy access_requests_deny_clients
on public.access_requests
for all
to anon, authenticated
using (false)
with check (false);

create trigger access_requests_touch_updated_at
before update on public.access_requests
for each row execute function private.touch_profile();

create or replace function private.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = excluded.full_name,
        updated_at = now();

  insert into public.access_requests (
    project_id,
    user_id,
    email,
    full_name,
    requested_role,
    status
  )
  select
    projects.id,
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    'visitante',
    'pending'
  from public.projects
  where projects.slug = 'alto-do-jeriva'
  on conflict (project_id, user_id) do update
    set email = excluded.email,
        full_name = excluded.full_name,
        updated_at = now();

  return new;
end;
$$;

revoke all on function private.handle_new_auth_user() from public, anon, authenticated;

-- Inclui contas que já existam, mas ainda não tenham vínculo com o projeto.
insert into public.access_requests (
  project_id,
  user_id,
  email,
  full_name,
  requested_role,
  status
)
select
  projects.id,
  profiles.id,
  profiles.email,
  profiles.full_name,
  'visitante',
  'pending'
from public.projects
cross join public.profiles
where projects.slug = 'alto-do-jeriva'
  and not exists (
    select 1
    from public.project_members
    where project_members.project_id = projects.id
      and project_members.user_id = profiles.id
  )
on conflict (project_id, user_id) do nothing;
